name: "Continuous Deployment"
on: 
  workflow_run: 
    branches: 
      - main
    types: 
      - completed
    workflows: 
      - "Continuous Integration"
jobs: 
  deploy: 
    if: "${{ github.event.workflow_run.conclusion == 'success' }}"
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./test-ci-cd
    steps: 
      - 
        name: "Checkout source"
        uses: actions/checkout@v1
      - 
        cache: npm
        name: "Setup node"
        node-version: "16"
        uses: actions/setup-node@v2
        with: ~
      - 
        name: Install
        run: "npm install"
      - 
        name: Build
        run: yarn build
      - 
        name: "Deploy to Github Pages"
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          publish_dir: ./public
