name: Continuous Integration
on: push
jobs:
  lint:
    name: Check linting issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16.x
        env:
          RUNNER_TEMP: /tmp
        # Install package dependencies as defined in package.json file in root of project.
      - name: install
        run: yarn install

        # Run `gatsby build`.
      - name: linting
        run: yarn lint

# TODO: Add the test folder and check whether that is working
      # Run the Jest unit tests and generate a coverage report.
      # - name: test
      #   run: yarn test -- --coverage
